import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nervape Create NFT From Mibao Open API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Nervape Mint NFT Demo</h1>
        <h3>From Mibao Open API</h3>

        <div>
          <div>
            <h2>0. 搞点事情</h2>
            <p>
              为了不打破现有nervape后台原有数据结构，需确保‘新增’mNFT数据的meta
              data所指向的文件稳定，即 https://oss.jinse.cc/production/*。
            </p>
            <p>
              0.1 （白嫖）在mibao创作者平台创建cotaNFT，以获取稳定的
              https://oss.jinse.cc/production/* 文件 url
            </p>
            <p>
              0.2（使用）将cotaNFT的封面和3d文件url填入下面：cover_image_url、renderer字段中。
            </p>
            <p>
              0.3（结束）nervape管理后台合并mNFT铸造功能时，此前白嫖的mibao
              oss数据应一并存入s3中。
            </p>
          </div>

          <div>
            <h2>1. 上传图片</h2>
            <p>
              指向 NFT 封面文件 cover_image_url ：<input type="text" />
            </p>
            <p>
              指向 NFT 模型文件 renderer ：<input type="text" />
            </p>
            <h2>2. 创建模版</h2>
            <p>
              （一旦创建，不可修改）name : <input type="text" />
            </p>
            <p>
              （一旦创建，不可修改）description :<input type="text" />
            </p>
            <p>
              （一旦创建，不可修改）total :<input type="text" />
            </p>
            <p>
              <button> 创建mNFT </button>
            </p>
          </div>

          <div>
            <h2>3. 铸造 NFT 实例</h2>
            <p>
              目标token的uuid: token_class_uuid :<input type="text" />
            </p>
            <p>
              目标mint 地址: addresses :<input type="text" />
            </p>
            <p>
              <button> 铸造mNFT </button>
            </p>
          </div>

          <div>
            <h2>4. 更新 NFT 模版（一个月最多一次）</h2>
            <p>
              更新 NFT 封面文件 cover_image_url ：<input type="text" />
            </p>
            <p>
              更新 NFT 模型文件 renderer ：<input type="text" />
            </p>
            <p>
              <button> 更新mNFT </button>
            </p>
          </div>
        </div>
      </main>

      {/************************************** footer **************************************/}
      <footer className={styles.footer}>Powered by Nervape</footer>
    </div>
  );
};

export default Home;
